CREATE TABLE PRODUCT (
  PRODUCT_ID BIGSERIAL PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL,
  PRICE FLOAT NOT NULL,
  DESCRIPTION VARCHAR(250) NOT NULL,
  QUANTITY INTEGER
);

CREATE TABLE PRODUCT_IMAGE (
  IMAGE_ID BIGSERIAL NOT NULL,
  PRODUCT_ID INTEGER NOT NULL,
  IMAGE_URL VARCHAR(250) NOT NULL
);

CREATE TABLE REVIEWS (
    REVIEW_ID BIGSERIAL NOT NULL,
    REVIEWD_BY_ID INTEGER NOT NULL,
    REVIEW_TEXT VARCHAR(500)
);

CREATE TABLE REVIEW_IMAGES (
  IMAGE_ID INTEGER NOT NULL,
  REVIEW_ID BIGSERIAL NOT NULL,
  IMAGE_URL VARCHAR(250) NOT NULL
);